# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BulkWaterMeterDialog.ui'
#
# Created: Tue Sep 27 09:08:14 2016
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_BulkWaterMeterDialog(object):
    def setupUi(self, BulkWaterMeterDialog):
        BulkWaterMeterDialog.setObjectName(_fromUtf8("BulkWaterMeterDialog"))
        BulkWaterMeterDialog.resize(588, 400)
        BulkWaterMeterDialog.setMinimumSize(QtCore.QSize(588, 400))
        BulkWaterMeterDialog.setMaximumSize(QtCore.QSize(588, 400))
        self.buttonBox = QtGui.QDialogButtonBox(BulkWaterMeterDialog)
        self.buttonBox.setGeometry(QtCore.QRect(405, 360, 166, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.tabWidget = QtGui.QTabWidget(BulkWaterMeterDialog)
        self.tabWidget.setGeometry(QtCore.QRect(15, 10, 556, 331))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.meter_number_edit = QtGui.QLineEdit(self.tab)
        self.meter_number_edit.setGeometry(QtCore.QRect(25, 30, 196, 20))
        self.meter_number_edit.setObjectName(_fromUtf8("meter_number_edit"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(25, 15, 126, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(25, 235, 126, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.inspection_intervall_unit_cbox = QtGui.QComboBox(self.tab)
        self.inspection_intervall_unit_cbox.setGeometry(QtCore.QRect(25, 162, 196, 22))
        self.inspection_intervall_unit_cbox.setObjectName(_fromUtf8("inspection_intervall_unit_cbox"))
        self.label_15 = QtGui.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(270, 190, 126, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_21 = QtGui.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(270, 16, 126, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_14 = QtGui.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(270, 146, 126, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.installation_date_chbox = QtGui.QCheckBox(self.tab)
        self.installation_date_chbox.setGeometry(QtCore.QRect(25, 75, 26, 17))
        self.installation_date_chbox.setText(_fromUtf8(""))
        self.installation_date_chbox.setObjectName(_fromUtf8("installation_date_chbox"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(25, 55, 126, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.network_cbox = QtGui.QComboBox(self.tab)
        self.network_cbox.setGeometry(QtCore.QRect(270, 205, 196, 22))
        self.network_cbox.setObjectName(_fromUtf8("network_cbox"))
        self.date_of_last_inspection_chbox = QtGui.QCheckBox(self.tab)
        self.date_of_last_inspection_chbox.setGeometry(QtCore.QRect(25, 210, 26, 17))
        self.date_of_last_inspection_chbox.setText(_fromUtf8(""))
        self.date_of_last_inspection_chbox.setObjectName(_fromUtf8("date_of_last_inspection_chbox"))
        self.inspection_intervall_sbox = QtGui.QDoubleSpinBox(self.tab)
        self.inspection_intervall_sbox.setGeometry(QtCore.QRect(25, 115, 196, 22))
        self.inspection_intervall_sbox.setObjectName(_fromUtf8("inspection_intervall_sbox"))
        self.date_of_last_inspection_edit = QtGui.QDateEdit(self.tab)
        self.date_of_last_inspection_edit.setEnabled(False)
        self.date_of_last_inspection_edit.setGeometry(QtCore.QRect(50, 205, 171, 22))
        self.date_of_last_inspection_edit.setCalendarPopup(True)
        self.date_of_last_inspection_edit.setObjectName(_fromUtf8("date_of_last_inspection_edit"))
        self.label_13 = QtGui.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(25, 190, 126, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.status_change_date_edit = QtGui.QDateEdit(self.tab)
        self.status_change_date_edit.setEnabled(False)
        self.status_change_date_edit.setGeometry(QtCore.QRect(295, 31, 171, 22))
        self.status_change_date_edit.setCalendarPopup(True)
        self.status_change_date_edit.setObjectName(_fromUtf8("status_change_date_edit"))
        self.operating_state_cbox = QtGui.QComboBox(self.tab)
        self.operating_state_cbox.setGeometry(QtCore.QRect(25, 250, 196, 22))
        self.operating_state_cbox.setObjectName(_fromUtf8("operating_state_cbox"))
        self.installation_date_edit = QtGui.QDateEdit(self.tab)
        self.installation_date_edit.setEnabled(False)
        self.installation_date_edit.setGeometry(QtCore.QRect(50, 70, 171, 22))
        self.installation_date_edit.setCalendarPopup(True)
        self.installation_date_edit.setObjectName(_fromUtf8("installation_date_edit"))
        self.height_sbox = QtGui.QDoubleSpinBox(self.tab)
        self.height_sbox.setGeometry(QtCore.QRect(270, 160, 196, 22))
        self.height_sbox.setMinimum(-100.0)
        self.height_sbox.setMaximum(2000.0)
        self.height_sbox.setObjectName(_fromUtf8("height_sbox"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(25, 100, 126, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.status_change_date_chbox = QtGui.QCheckBox(self.tab)
        self.status_change_date_chbox.setGeometry(QtCore.QRect(270, 36, 26, 17))
        self.status_change_date_chbox.setText(_fromUtf8(""))
        self.status_change_date_chbox.setObjectName(_fromUtf8("status_change_date_chbox"))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(25, 145, 126, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.meter_class_cbox = QtGui.QComboBox(self.tab)
        self.meter_class_cbox.setGeometry(QtCore.QRect(270, 71, 196, 22))
        self.meter_class_cbox.setObjectName(_fromUtf8("meter_class_cbox"))
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(270, 56, 126, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.meter_type_cbox = QtGui.QComboBox(self.tab)
        self.meter_type_cbox.setGeometry(QtCore.QRect(270, 116, 196, 22))
        self.meter_type_cbox.setObjectName(_fromUtf8("meter_type_cbox"))
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(270, 101, 126, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))

        self.retranslateUi(BulkWaterMeterDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), BulkWaterMeterDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), BulkWaterMeterDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(BulkWaterMeterDialog)
        BulkWaterMeterDialog.setTabOrder(self.tabWidget, self.meter_number_edit)
        BulkWaterMeterDialog.setTabOrder(self.meter_number_edit, self.installation_date_chbox)
        BulkWaterMeterDialog.setTabOrder(self.installation_date_chbox, self.installation_date_edit)
        BulkWaterMeterDialog.setTabOrder(self.installation_date_edit, self.inspection_intervall_sbox)
        BulkWaterMeterDialog.setTabOrder(self.inspection_intervall_sbox, self.inspection_intervall_unit_cbox)
        BulkWaterMeterDialog.setTabOrder(self.inspection_intervall_unit_cbox, self.date_of_last_inspection_chbox)
        BulkWaterMeterDialog.setTabOrder(self.date_of_last_inspection_chbox, self.date_of_last_inspection_edit)
        BulkWaterMeterDialog.setTabOrder(self.date_of_last_inspection_edit, self.operating_state_cbox)
        BulkWaterMeterDialog.setTabOrder(self.operating_state_cbox, self.status_change_date_chbox)
        BulkWaterMeterDialog.setTabOrder(self.status_change_date_chbox, self.status_change_date_edit)
        BulkWaterMeterDialog.setTabOrder(self.status_change_date_edit, self.meter_class_cbox)
        BulkWaterMeterDialog.setTabOrder(self.meter_class_cbox, self.meter_type_cbox)
        BulkWaterMeterDialog.setTabOrder(self.meter_type_cbox, self.height_sbox)
        BulkWaterMeterDialog.setTabOrder(self.height_sbox, self.network_cbox)

    def retranslateUi(self, BulkWaterMeterDialog):
        BulkWaterMeterDialog.setWindowTitle(_translate("BulkWaterMeterDialog", "Add / Edit Bulk Water Meter", None))
        self.label.setText(_translate("BulkWaterMeterDialog", "Meter Number", None))
        self.label_7.setText(_translate("BulkWaterMeterDialog", "Operating State", None))
        self.label_15.setText(_translate("BulkWaterMeterDialog", "Network", None))
        self.label_21.setText(_translate("BulkWaterMeterDialog", "Date of Status Change", None))
        self.label_14.setText(_translate("BulkWaterMeterDialog", "Height [m]", None))
        self.label_3.setText(_translate("BulkWaterMeterDialog", "Installation Date", None))
        self.date_of_last_inspection_edit.setDisplayFormat(_translate("BulkWaterMeterDialog", "yyyy-MM-dd", None))
        self.label_13.setText(_translate("BulkWaterMeterDialog", "Date of Last Inspection", None))
        self.status_change_date_edit.setDisplayFormat(_translate("BulkWaterMeterDialog", "yyyy-MM-dd", None))
        self.installation_date_edit.setDisplayFormat(_translate("BulkWaterMeterDialog", "yyyy-MM-dd", None))
        self.label_5.setText(_translate("BulkWaterMeterDialog", "Inspection Interval", None))
        self.label_6.setText(_translate("BulkWaterMeterDialog", "Inspection Interval Unit", None))
        self.label_9.setText(_translate("BulkWaterMeterDialog", "Meter Class", None))
        self.label_10.setText(_translate("BulkWaterMeterDialog", "Meter Type", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("BulkWaterMeterDialog", "Description", None))

import resources_rc
