# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CustomerManagementForm.ui'
#
# Created: Mon Oct 24 13:45:34 2016
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CustomerManagementForm(object):
    def setupUi(self, CustomerManagementForm):
        CustomerManagementForm.setObjectName(_fromUtf8("CustomerManagementForm"))
        CustomerManagementForm.resize(553, 388)
        self.unassign_cust_button = QtGui.QPushButton(CustomerManagementForm)
        self.unassign_cust_button.setGeometry(QtCore.QRect(290, 205, 25, 25))
        self.unassign_cust_button.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/wnt/minus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.unassign_cust_button.setIcon(icon)
        self.unassign_cust_button.setObjectName(_fromUtf8("unassign_cust_button"))
        self.assigned_cust_twidget = QtGui.QTableWidget(CustomerManagementForm)
        self.assigned_cust_twidget.setGeometry(QtCore.QRect(15, 235, 526, 141))
        self.assigned_cust_twidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.assigned_cust_twidget.setAlternatingRowColors(True)
        self.assigned_cust_twidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.assigned_cust_twidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.assigned_cust_twidget.setObjectName(_fromUtf8("assigned_cust_twidget"))
        self.assigned_cust_twidget.setColumnCount(8)
        self.assigned_cust_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.assigned_cust_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.assigned_cust_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.assigned_cust_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.assigned_cust_twidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.assigned_cust_twidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.assigned_cust_twidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.assigned_cust_twidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.assigned_cust_twidget.setHorizontalHeaderItem(7, item)
        self.assign_cust_button = QtGui.QPushButton(CustomerManagementForm)
        self.assign_cust_button.setGeometry(QtCore.QRect(255, 205, 25, 25))
        self.assign_cust_button.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/wnt/plus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.assign_cust_button.setIcon(icon1)
        self.assign_cust_button.setObjectName(_fromUtf8("assign_cust_button"))
        self.label_16 = QtGui.QLabel(CustomerManagementForm)
        self.label_16.setGeometry(QtCore.QRect(15, 220, 136, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.registered_cust_twidget = QtGui.QTableWidget(CustomerManagementForm)
        self.registered_cust_twidget.setGeometry(QtCore.QRect(15, 80, 526, 121))
        self.registered_cust_twidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.registered_cust_twidget.setAlternatingRowColors(True)
        self.registered_cust_twidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.registered_cust_twidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.registered_cust_twidget.setObjectName(_fromUtf8("registered_cust_twidget"))
        self.registered_cust_twidget.setColumnCount(8)
        self.registered_cust_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.registered_cust_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.registered_cust_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.registered_cust_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.registered_cust_twidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.registered_cust_twidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.registered_cust_twidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.registered_cust_twidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.registered_cust_twidget.setHorizontalHeaderItem(7, item)
        self.label_17 = QtGui.QLabel(CustomerManagementForm)
        self.label_17.setGeometry(QtCore.QRect(15, 65, 171, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.search_term_edit = QtGui.QLineEdit(CustomerManagementForm)
        self.search_term_edit.setGeometry(QtCore.QRect(140, 30, 176, 20))
        self.search_term_edit.setObjectName(_fromUtf8("search_term_edit"))
        self.label_18 = QtGui.QLabel(CustomerManagementForm)
        self.label_18.setGeometry(QtCore.QRect(140, 15, 171, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.search_button = QtGui.QPushButton(CustomerManagementForm)
        self.search_button.setGeometry(QtCore.QRect(320, 27, 25, 25))
        self.search_button.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/wnt/search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_button.setIcon(icon2)
        self.search_button.setObjectName(_fromUtf8("search_button"))
        self.id_rbutton = QtGui.QRadioButton(CustomerManagementForm)
        self.id_rbutton.setGeometry(QtCore.QRect(20, 15, 82, 17))
        self.id_rbutton.setChecked(False)
        self.id_rbutton.setObjectName(_fromUtf8("id_rbutton"))
        self.buttonGroup = QtGui.QButtonGroup(CustomerManagementForm)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.id_rbutton)
        self.name_rbutton = QtGui.QRadioButton(CustomerManagementForm)
        self.name_rbutton.setGeometry(QtCore.QRect(20, 35, 82, 17))
        self.name_rbutton.setChecked(True)
        self.name_rbutton.setObjectName(_fromUtf8("name_rbutton"))
        self.buttonGroup.addButton(self.name_rbutton)

        self.retranslateUi(CustomerManagementForm)
        QtCore.QMetaObject.connectSlotsByName(CustomerManagementForm)
        CustomerManagementForm.setTabOrder(self.id_rbutton, self.name_rbutton)
        CustomerManagementForm.setTabOrder(self.name_rbutton, self.search_term_edit)
        CustomerManagementForm.setTabOrder(self.search_term_edit, self.search_button)
        CustomerManagementForm.setTabOrder(self.search_button, self.registered_cust_twidget)
        CustomerManagementForm.setTabOrder(self.registered_cust_twidget, self.assign_cust_button)
        CustomerManagementForm.setTabOrder(self.assign_cust_button, self.unassign_cust_button)
        CustomerManagementForm.setTabOrder(self.unassign_cust_button, self.assigned_cust_twidget)

    def retranslateUi(self, CustomerManagementForm):
        CustomerManagementForm.setWindowTitle(_translate("CustomerManagementForm", "Form", None))
        self.unassign_cust_button.setToolTip(_translate("CustomerManagementForm", "Unassign Customer", None))
        item = self.assigned_cust_twidget.horizontalHeaderItem(0)
        item.setText(_translate("CustomerManagementForm", "ID", None))
        item = self.assigned_cust_twidget.horizontalHeaderItem(1)
        item.setText(_translate("CustomerManagementForm", "Name", None))
        item = self.assigned_cust_twidget.horizontalHeaderItem(2)
        item.setText(_translate("CustomerManagementForm", "Address", None))
        item = self.assigned_cust_twidget.horizontalHeaderItem(3)
        item.setText(_translate("CustomerManagementForm", "House No", None))
        item = self.assigned_cust_twidget.horizontalHeaderItem(4)
        item.setText(_translate("CustomerManagementForm", "City", None))
        item = self.assigned_cust_twidget.horizontalHeaderItem(5)
        item.setText(_translate("CustomerManagementForm", "CAN", None))
        item = self.assigned_cust_twidget.horizontalHeaderItem(6)
        item.setText(_translate("CustomerManagementForm", "Status", None))
        item = self.assigned_cust_twidget.horizontalHeaderItem(7)
        item.setText(_translate("CustomerManagementForm", "Tariff Category", None))
        self.assign_cust_button.setToolTip(_translate("CustomerManagementForm", "Assign Customer", None))
        self.label_16.setText(_translate("CustomerManagementForm", "Assigned Customer(s)", None))
        item = self.registered_cust_twidget.horizontalHeaderItem(0)
        item.setText(_translate("CustomerManagementForm", "ID", None))
        item = self.registered_cust_twidget.horizontalHeaderItem(1)
        item.setText(_translate("CustomerManagementForm", "Name", None))
        item = self.registered_cust_twidget.horizontalHeaderItem(2)
        item.setText(_translate("CustomerManagementForm", "Address", None))
        item = self.registered_cust_twidget.horizontalHeaderItem(3)
        item.setText(_translate("CustomerManagementForm", "House No", None))
        item = self.registered_cust_twidget.horizontalHeaderItem(4)
        item.setText(_translate("CustomerManagementForm", "City", None))
        item = self.registered_cust_twidget.horizontalHeaderItem(5)
        item.setText(_translate("CustomerManagementForm", "CAN", None))
        item = self.registered_cust_twidget.horizontalHeaderItem(6)
        item.setText(_translate("CustomerManagementForm", "Status", None))
        item = self.registered_cust_twidget.horizontalHeaderItem(7)
        item.setText(_translate("CustomerManagementForm", "Tariff Category", None))
        self.label_17.setText(_translate("CustomerManagementForm", "Registered Customer(s)", None))
        self.label_18.setText(_translate("CustomerManagementForm", "Search Term", None))
        self.search_button.setToolTip(_translate("CustomerManagementForm", "Add Damage", None))
        self.id_rbutton.setText(_translate("CustomerManagementForm", "ID / CAN", None))
        self.name_rbutton.setText(_translate("CustomerManagementForm", "Name", None))

import resources_rc
