# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FlatrateConnectionDialog.ui'
#
# Created: Thu Oct 13 07:00:59 2016
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FlatrateConnectionDialog(object):
    def setupUi(self, FlatrateConnectionDialog):
        FlatrateConnectionDialog.setObjectName(_fromUtf8("FlatrateConnectionDialog"))
        FlatrateConnectionDialog.resize(588, 532)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FlatrateConnectionDialog.sizePolicy().hasHeightForWidth())
        FlatrateConnectionDialog.setSizePolicy(sizePolicy)
        FlatrateConnectionDialog.setMinimumSize(QtCore.QSize(588, 450))
        FlatrateConnectionDialog.setMaximumSize(QtCore.QSize(588, 640))
        self.buttonBox = QtGui.QDialogButtonBox(FlatrateConnectionDialog)
        self.buttonBox.setGeometry(QtCore.QRect(390, 490, 166, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.tabWidget = QtGui.QTabWidget(FlatrateConnectionDialog)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 561, 471))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.inspection_intervall_sbox = QtGui.QDoubleSpinBox(self.tab)
        self.inspection_intervall_sbox.setGeometry(QtCore.QRect(265, 70, 196, 22))
        self.inspection_intervall_sbox.setObjectName(_fromUtf8("inspection_intervall_sbox"))
        self.installation_date_edit = QtGui.QDateEdit(self.tab)
        self.installation_date_edit.setEnabled(False)
        self.installation_date_edit.setGeometry(QtCore.QRect(45, 350, 171, 22))
        self.installation_date_edit.setCalendarPopup(True)
        self.installation_date_edit.setObjectName(_fromUtf8("installation_date_edit"))
        self.installation_date_chbox = QtGui.QCheckBox(self.tab)
        self.installation_date_chbox.setGeometry(QtCore.QRect(20, 355, 26, 17))
        self.installation_date_chbox.setText(_fromUtf8(""))
        self.installation_date_chbox.setObjectName(_fromUtf8("installation_date_chbox"))
        self.connection_no_edit = QtGui.QLineEdit(self.tab)
        self.connection_no_edit.setGeometry(QtCore.QRect(20, 30, 196, 20))
        self.connection_no_edit.setObjectName(_fromUtf8("connection_no_edit"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 335, 126, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(265, 55, 126, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 15, 141, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.inspection_intervall_unit_cbox = QtGui.QComboBox(self.tab)
        self.inspection_intervall_unit_cbox.setGeometry(QtCore.QRect(265, 110, 196, 22))
        self.inspection_intervall_unit_cbox.setObjectName(_fromUtf8("inspection_intervall_unit_cbox"))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(265, 95, 126, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(265, 175, 126, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.operating_state_cbox = QtGui.QComboBox(self.tab)
        self.operating_state_cbox.setGeometry(QtCore.QRect(265, 190, 196, 22))
        self.operating_state_cbox.setObjectName(_fromUtf8("operating_state_cbox"))
        self.height_sbox = QtGui.QDoubleSpinBox(self.tab)
        self.height_sbox.setGeometry(QtCore.QRect(265, 270, 196, 22))
        self.height_sbox.setMinimum(-100.0)
        self.height_sbox.setMaximum(2000.0)
        self.height_sbox.setObjectName(_fromUtf8("height_sbox"))
        self.label_14 = QtGui.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(265, 255, 126, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(265, 295, 126, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.network_cbox = QtGui.QComboBox(self.tab)
        self.network_cbox.setGeometry(QtCore.QRect(265, 310, 196, 22))
        self.network_cbox.setObjectName(_fromUtf8("network_cbox"))
        self.date_of_last_inspection_edit = QtGui.QDateEdit(self.tab)
        self.date_of_last_inspection_edit.setEnabled(False)
        self.date_of_last_inspection_edit.setGeometry(QtCore.QRect(290, 150, 171, 22))
        self.date_of_last_inspection_edit.setCalendarPopup(True)
        self.date_of_last_inspection_edit.setObjectName(_fromUtf8("date_of_last_inspection_edit"))
        self.date_of_last_inspection_chbox = QtGui.QCheckBox(self.tab)
        self.date_of_last_inspection_chbox.setGeometry(QtCore.QRect(265, 155, 26, 17))
        self.date_of_last_inspection_chbox.setText(_fromUtf8(""))
        self.date_of_last_inspection_chbox.setObjectName(_fromUtf8("date_of_last_inspection_chbox"))
        self.label_13 = QtGui.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(265, 135, 126, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 55, 211, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.plot_no_edit = QtGui.QLineEdit(self.tab)
        self.plot_no_edit.setGeometry(QtCore.QRect(20, 150, 196, 20))
        self.plot_no_edit.setObjectName(_fromUtf8("plot_no_edit"))
        self.label_16 = QtGui.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(20, 135, 141, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.district_edit = QtGui.QLineEdit(self.tab)
        self.district_edit.setGeometry(QtCore.QRect(20, 190, 196, 20))
        self.district_edit.setObjectName(_fromUtf8("district_edit"))
        self.label_17 = QtGui.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(20, 175, 141, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.zone_edit = QtGui.QLineEdit(self.tab)
        self.zone_edit.setGeometry(QtCore.QRect(20, 230, 196, 20))
        self.zone_edit.setObjectName(_fromUtf8("zone_edit"))
        self.label_18 = QtGui.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(20, 215, 141, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.ward_edit = QtGui.QLineEdit(self.tab)
        self.ward_edit.setGeometry(QtCore.QRect(20, 270, 196, 20))
        self.ward_edit.setText(_fromUtf8(""))
        self.ward_edit.setObjectName(_fromUtf8("ward_edit"))
        self.label_19 = QtGui.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(20, 255, 141, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.tab)
        self.label_20.setGeometry(QtCore.QRect(20, 295, 141, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.street_edit = QtGui.QLineEdit(self.tab)
        self.street_edit.setGeometry(QtCore.QRect(20, 310, 196, 20))
        self.street_edit.setText(_fromUtf8(""))
        self.street_edit.setObjectName(_fromUtf8("street_edit"))
        self.label_22 = QtGui.QLabel(self.tab)
        self.label_22.setGeometry(QtCore.QRect(265, 15, 126, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.date_of_first_use_edit = QtGui.QDateEdit(self.tab)
        self.date_of_first_use_edit.setEnabled(False)
        self.date_of_first_use_edit.setGeometry(QtCore.QRect(290, 30, 171, 22))
        self.date_of_first_use_edit.setCalendarPopup(True)
        self.date_of_first_use_edit.setObjectName(_fromUtf8("date_of_first_use_edit"))
        self.date_of_first_use_chbox = QtGui.QCheckBox(self.tab)
        self.date_of_first_use_chbox.setGeometry(QtCore.QRect(265, 35, 26, 17))
        self.date_of_first_use_chbox.setText(_fromUtf8(""))
        self.date_of_first_use_chbox.setObjectName(_fromUtf8("date_of_first_use_chbox"))
        self.status_change_date_chbox = QtGui.QCheckBox(self.tab)
        self.status_change_date_chbox.setGeometry(QtCore.QRect(265, 235, 26, 17))
        self.status_change_date_chbox.setText(_fromUtf8(""))
        self.status_change_date_chbox.setObjectName(_fromUtf8("status_change_date_chbox"))
        self.label_21 = QtGui.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(265, 215, 126, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.status_change_date_edit = QtGui.QDateEdit(self.tab)
        self.status_change_date_edit.setEnabled(False)
        self.status_change_date_edit.setGeometry(QtCore.QRect(290, 230, 171, 22))
        self.status_change_date_edit.setCalendarPopup(True)
        self.status_change_date_edit.setObjectName(_fromUtf8("status_change_date_edit"))
        self.view_maxcom_button = QtGui.QPushButton(self.tab)
        self.view_maxcom_button.setGeometry(QtCore.QRect(190, 95, 25, 25))
        self.view_maxcom_button.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/wnt/eye.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.view_maxcom_button.setIcon(icon)
        self.view_maxcom_button.setObjectName(_fromUtf8("view_maxcom_button"))
        self.verify_button = QtGui.QPushButton(self.tab)
        self.verify_button.setGeometry(QtCore.QRect(160, 95, 25, 25))
        self.verify_button.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/wnt/verify.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.verify_button.setIcon(icon1)
        self.verify_button.setObjectName(_fromUtf8("verify_button"))
        self.control_no_sbox = QtGui.QSpinBox(self.tab)
        self.control_no_sbox.setGeometry(QtCore.QRect(20, 70, 196, 22))
        self.control_no_sbox.setMinimum(-1)
        self.control_no_sbox.setMaximum(8000000)
        self.control_no_sbox.setProperty("value", -1)
        self.control_no_sbox.setObjectName(_fromUtf8("control_no_sbox"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))

        self.retranslateUi(FlatrateConnectionDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), FlatrateConnectionDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), FlatrateConnectionDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(FlatrateConnectionDialog)
        FlatrateConnectionDialog.setTabOrder(self.tabWidget, self.connection_no_edit)
        FlatrateConnectionDialog.setTabOrder(self.connection_no_edit, self.control_no_sbox)
        FlatrateConnectionDialog.setTabOrder(self.control_no_sbox, self.verify_button)
        FlatrateConnectionDialog.setTabOrder(self.verify_button, self.view_maxcom_button)
        FlatrateConnectionDialog.setTabOrder(self.view_maxcom_button, self.plot_no_edit)
        FlatrateConnectionDialog.setTabOrder(self.plot_no_edit, self.district_edit)
        FlatrateConnectionDialog.setTabOrder(self.district_edit, self.zone_edit)
        FlatrateConnectionDialog.setTabOrder(self.zone_edit, self.ward_edit)
        FlatrateConnectionDialog.setTabOrder(self.ward_edit, self.street_edit)
        FlatrateConnectionDialog.setTabOrder(self.street_edit, self.installation_date_chbox)
        FlatrateConnectionDialog.setTabOrder(self.installation_date_chbox, self.installation_date_edit)
        FlatrateConnectionDialog.setTabOrder(self.installation_date_edit, self.date_of_first_use_chbox)
        FlatrateConnectionDialog.setTabOrder(self.date_of_first_use_chbox, self.date_of_first_use_edit)
        FlatrateConnectionDialog.setTabOrder(self.date_of_first_use_edit, self.inspection_intervall_sbox)
        FlatrateConnectionDialog.setTabOrder(self.inspection_intervall_sbox, self.inspection_intervall_unit_cbox)
        FlatrateConnectionDialog.setTabOrder(self.inspection_intervall_unit_cbox, self.date_of_last_inspection_chbox)
        FlatrateConnectionDialog.setTabOrder(self.date_of_last_inspection_chbox, self.date_of_last_inspection_edit)
        FlatrateConnectionDialog.setTabOrder(self.date_of_last_inspection_edit, self.operating_state_cbox)
        FlatrateConnectionDialog.setTabOrder(self.operating_state_cbox, self.status_change_date_chbox)
        FlatrateConnectionDialog.setTabOrder(self.status_change_date_chbox, self.status_change_date_edit)
        FlatrateConnectionDialog.setTabOrder(self.status_change_date_edit, self.height_sbox)
        FlatrateConnectionDialog.setTabOrder(self.height_sbox, self.network_cbox)
        FlatrateConnectionDialog.setTabOrder(self.network_cbox, self.buttonBox)

    def retranslateUi(self, FlatrateConnectionDialog):
        FlatrateConnectionDialog.setWindowTitle(_translate("FlatrateConnectionDialog", "Add / Edit Flatrate Connection", None))
        self.installation_date_edit.setDisplayFormat(_translate("FlatrateConnectionDialog", "yyyy-MM-dd", None))
        self.label_3.setText(_translate("FlatrateConnectionDialog", "Installation Date", None))
        self.label_5.setText(_translate("FlatrateConnectionDialog", "Inspection Interval", None))
        self.label.setText(_translate("FlatrateConnectionDialog", "Flatrate Connection Number", None))
        self.label_6.setText(_translate("FlatrateConnectionDialog", "Inspection Interval Unit", None))
        self.label_7.setText(_translate("FlatrateConnectionDialog", "Operating State", None))
        self.label_14.setText(_translate("FlatrateConnectionDialog", "Height [m]", None))
        self.label_15.setText(_translate("FlatrateConnectionDialog", "Network", None))
        self.date_of_last_inspection_edit.setDisplayFormat(_translate("FlatrateConnectionDialog", "yyyy-MM-dd", None))
        self.label_13.setText(_translate("FlatrateConnectionDialog", "Date of Last Inspection", None))
        self.label_2.setText(_translate("FlatrateConnectionDialog", "Application Control No. (from MAXCOM)", None))
        self.label_16.setText(_translate("FlatrateConnectionDialog", "Plot Number", None))
        self.label_17.setText(_translate("FlatrateConnectionDialog", "District", None))
        self.label_18.setText(_translate("FlatrateConnectionDialog", "Zone", None))
        self.label_19.setText(_translate("FlatrateConnectionDialog", "Ward", None))
        self.label_20.setText(_translate("FlatrateConnectionDialog", "Street", None))
        self.label_22.setText(_translate("FlatrateConnectionDialog", "Date of First Use", None))
        self.date_of_first_use_edit.setDisplayFormat(_translate("FlatrateConnectionDialog", "yyyy-MM-dd", None))
        self.label_21.setText(_translate("FlatrateConnectionDialog", "Date of Status Change", None))
        self.status_change_date_edit.setDisplayFormat(_translate("FlatrateConnectionDialog", "yyyy-MM-dd", None))
        self.view_maxcom_button.setToolTip(_translate("FlatrateConnectionDialog", "View Application Details at MAXCOM", None))
        self.verify_button.setToolTip(_translate("FlatrateConnectionDialog", "Verify Control Number", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("FlatrateConnectionDialog", "Description", None))

import resources_rc
