# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LineCasingDialog.ui'
#
# Created: Tue Sep 27 09:10:08 2016
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_LineCasingDialog(object):
    def setupUi(self, LineCasingDialog):
        LineCasingDialog.setObjectName(_fromUtf8("LineCasingDialog"))
        LineCasingDialog.resize(588, 390)
        LineCasingDialog.setMinimumSize(QtCore.QSize(588, 390))
        LineCasingDialog.setMaximumSize(QtCore.QSize(588, 480))
        self.buttonBox = QtGui.QDialogButtonBox(LineCasingDialog)
        self.buttonBox.setGeometry(QtCore.QRect(405, 340, 166, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.tabWidget = QtGui.QTabWidget(LineCasingDialog)
        self.tabWidget.setGeometry(QtCore.QRect(15, 10, 556, 321))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.inspection_intervall_sbox = QtGui.QDoubleSpinBox(self.tab)
        self.inspection_intervall_sbox.setGeometry(QtCore.QRect(20, 110, 196, 22))
        self.inspection_intervall_sbox.setObjectName(_fromUtf8("inspection_intervall_sbox"))
        self.installation_date_edit = QtGui.QDateEdit(self.tab)
        self.installation_date_edit.setEnabled(False)
        self.installation_date_edit.setGeometry(QtCore.QRect(45, 70, 171, 22))
        self.installation_date_edit.setCalendarPopup(True)
        self.installation_date_edit.setObjectName(_fromUtf8("installation_date_edit"))
        self.installation_date_chbox = QtGui.QCheckBox(self.tab)
        self.installation_date_chbox.setGeometry(QtCore.QRect(20, 75, 26, 17))
        self.installation_date_chbox.setText(_fromUtf8(""))
        self.installation_date_chbox.setObjectName(_fromUtf8("installation_date_chbox"))
        self.line_casing_number_edit = QtGui.QLineEdit(self.tab)
        self.line_casing_number_edit.setGeometry(QtCore.QRect(20, 30, 196, 20))
        self.line_casing_number_edit.setObjectName(_fromUtf8("line_casing_number_edit"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 55, 126, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(20, 95, 126, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 15, 126, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.inspection_intervall_unit_cbox = QtGui.QComboBox(self.tab)
        self.inspection_intervall_unit_cbox.setGeometry(QtCore.QRect(20, 155, 196, 22))
        self.inspection_intervall_unit_cbox.setObjectName(_fromUtf8("inspection_intervall_unit_cbox"))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(20, 140, 126, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(270, 15, 126, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.casing_type_cbox = QtGui.QComboBox(self.tab)
        self.casing_type_cbox.setGeometry(QtCore.QRect(270, 30, 196, 22))
        self.casing_type_cbox.setObjectName(_fromUtf8("casing_type_cbox"))
        self.label_15 = QtGui.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(270, 226, 126, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.network_cbox = QtGui.QComboBox(self.tab)
        self.network_cbox.setGeometry(QtCore.QRect(270, 241, 196, 22))
        self.network_cbox.setObjectName(_fromUtf8("network_cbox"))
        self.date_of_last_inspection_edit = QtGui.QDateEdit(self.tab)
        self.date_of_last_inspection_edit.setEnabled(False)
        self.date_of_last_inspection_edit.setGeometry(QtCore.QRect(45, 200, 171, 22))
        self.date_of_last_inspection_edit.setCalendarPopup(True)
        self.date_of_last_inspection_edit.setObjectName(_fromUtf8("date_of_last_inspection_edit"))
        self.date_of_last_inspection_chbox = QtGui.QCheckBox(self.tab)
        self.date_of_last_inspection_chbox.setGeometry(QtCore.QRect(20, 205, 26, 17))
        self.date_of_last_inspection_chbox.setText(_fromUtf8(""))
        self.date_of_last_inspection_chbox.setObjectName(_fromUtf8("date_of_last_inspection_chbox"))
        self.label_13 = QtGui.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(20, 185, 126, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.length_sbox = QtGui.QDoubleSpinBox(self.tab)
        self.length_sbox.setGeometry(QtCore.QRect(270, 71, 196, 22))
        self.length_sbox.setDecimals(1)
        self.length_sbox.setMaximum(500.0)
        self.length_sbox.setObjectName(_fromUtf8("length_sbox"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(270, 56, 126, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.outer_height_sbox = QtGui.QDoubleSpinBox(self.tab)
        self.outer_height_sbox.setGeometry(QtCore.QRect(270, 111, 196, 22))
        self.outer_height_sbox.setDecimals(1)
        self.outer_height_sbox.setMaximum(500.0)
        self.outer_height_sbox.setObjectName(_fromUtf8("outer_height_sbox"))
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(270, 96, 126, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(270, 141, 126, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.outer_width_sbox = QtGui.QDoubleSpinBox(self.tab)
        self.outer_width_sbox.setGeometry(QtCore.QRect(270, 156, 196, 22))
        self.outer_width_sbox.setDecimals(1)
        self.outer_width_sbox.setMaximum(500.0)
        self.outer_width_sbox.setObjectName(_fromUtf8("outer_width_sbox"))
        self.jacket_pipe_diameter_cbox = QtGui.QComboBox(self.tab)
        self.jacket_pipe_diameter_cbox.setGeometry(QtCore.QRect(270, 201, 196, 22))
        self.jacket_pipe_diameter_cbox.setObjectName(_fromUtf8("jacket_pipe_diameter_cbox"))
        self.label_16 = QtGui.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(270, 186, 126, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))

        self.retranslateUi(LineCasingDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), LineCasingDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), LineCasingDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(LineCasingDialog)
        LineCasingDialog.setTabOrder(self.tabWidget, self.line_casing_number_edit)
        LineCasingDialog.setTabOrder(self.line_casing_number_edit, self.installation_date_chbox)
        LineCasingDialog.setTabOrder(self.installation_date_chbox, self.installation_date_edit)
        LineCasingDialog.setTabOrder(self.installation_date_edit, self.inspection_intervall_sbox)
        LineCasingDialog.setTabOrder(self.inspection_intervall_sbox, self.inspection_intervall_unit_cbox)
        LineCasingDialog.setTabOrder(self.inspection_intervall_unit_cbox, self.date_of_last_inspection_chbox)
        LineCasingDialog.setTabOrder(self.date_of_last_inspection_chbox, self.date_of_last_inspection_edit)
        LineCasingDialog.setTabOrder(self.date_of_last_inspection_edit, self.casing_type_cbox)
        LineCasingDialog.setTabOrder(self.casing_type_cbox, self.length_sbox)
        LineCasingDialog.setTabOrder(self.length_sbox, self.outer_height_sbox)
        LineCasingDialog.setTabOrder(self.outer_height_sbox, self.outer_width_sbox)
        LineCasingDialog.setTabOrder(self.outer_width_sbox, self.jacket_pipe_diameter_cbox)
        LineCasingDialog.setTabOrder(self.jacket_pipe_diameter_cbox, self.network_cbox)

    def retranslateUi(self, LineCasingDialog):
        LineCasingDialog.setWindowTitle(_translate("LineCasingDialog", "Add / Edit Line Casing", None))
        self.installation_date_edit.setDisplayFormat(_translate("LineCasingDialog", "yyyy-MM-dd", None))
        self.label_3.setText(_translate("LineCasingDialog", "Installation Date", None))
        self.label_5.setText(_translate("LineCasingDialog", "Inspection Interval", None))
        self.label.setText(_translate("LineCasingDialog", "Line Casing Number", None))
        self.label_6.setText(_translate("LineCasingDialog", "Inspection Interval Unit", None))
        self.label_9.setText(_translate("LineCasingDialog", "Casing Type", None))
        self.label_15.setText(_translate("LineCasingDialog", "Network", None))
        self.date_of_last_inspection_edit.setDisplayFormat(_translate("LineCasingDialog", "yyyy-MM-dd", None))
        self.label_13.setText(_translate("LineCasingDialog", "Date of Last Inspection", None))
        self.label_2.setText(_translate("LineCasingDialog", "Length [m]", None))
        self.label_7.setText(_translate("LineCasingDialog", "Outer Height [m]", None))
        self.label_8.setText(_translate("LineCasingDialog", "Outer Width [mm]", None))
        self.label_16.setText(_translate("LineCasingDialog", "Jacket Pipe Diameter", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("LineCasingDialog", "Description", None))

import resources_rc
