# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ManholeDialog.ui'
#
# Created: Tue Sep 27 09:10:32 2016
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ManholeDialog(object):
    def setupUi(self, ManholeDialog):
        ManholeDialog.setObjectName(_fromUtf8("ManholeDialog"))
        ManholeDialog.resize(588, 450)
        ManholeDialog.setMinimumSize(QtCore.QSize(588, 450))
        ManholeDialog.setMaximumSize(QtCore.QSize(588, 480))
        self.buttonBox = QtGui.QDialogButtonBox(ManholeDialog)
        self.buttonBox.setGeometry(QtCore.QRect(405, 400, 166, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.tabWidget = QtGui.QTabWidget(ManholeDialog)
        self.tabWidget.setGeometry(QtCore.QRect(15, 10, 556, 371))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.inspection_intervall_sbox = QtGui.QDoubleSpinBox(self.tab)
        self.inspection_intervall_sbox.setGeometry(QtCore.QRect(20, 115, 196, 22))
        self.inspection_intervall_sbox.setObjectName(_fromUtf8("inspection_intervall_sbox"))
        self.installation_date_edit = QtGui.QDateEdit(self.tab)
        self.installation_date_edit.setEnabled(False)
        self.installation_date_edit.setGeometry(QtCore.QRect(45, 75, 171, 22))
        self.installation_date_edit.setCalendarPopup(True)
        self.installation_date_edit.setObjectName(_fromUtf8("installation_date_edit"))
        self.installation_date_chbox = QtGui.QCheckBox(self.tab)
        self.installation_date_chbox.setGeometry(QtCore.QRect(20, 80, 26, 17))
        self.installation_date_chbox.setText(_fromUtf8(""))
        self.installation_date_chbox.setObjectName(_fromUtf8("installation_date_chbox"))
        self.manhole_no_edit = QtGui.QLineEdit(self.tab)
        self.manhole_no_edit.setGeometry(QtCore.QRect(20, 30, 196, 20))
        self.manhole_no_edit.setObjectName(_fromUtf8("manhole_no_edit"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 126, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(20, 100, 126, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 15, 126, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.inspection_intervall_unit_cbox = QtGui.QComboBox(self.tab)
        self.inspection_intervall_unit_cbox.setGeometry(QtCore.QRect(20, 160, 196, 22))
        self.inspection_intervall_unit_cbox.setObjectName(_fromUtf8("inspection_intervall_unit_cbox"))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(20, 145, 126, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(20, 235, 126, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.operating_state_cbox = QtGui.QComboBox(self.tab)
        self.operating_state_cbox.setGeometry(QtCore.QRect(20, 250, 196, 22))
        self.operating_state_cbox.setObjectName(_fromUtf8("operating_state_cbox"))
        self.status_change_date_edit = QtGui.QDateEdit(self.tab)
        self.status_change_date_edit.setEnabled(False)
        self.status_change_date_edit.setGeometry(QtCore.QRect(45, 300, 171, 22))
        self.status_change_date_edit.setCalendarPopup(True)
        self.status_change_date_edit.setObjectName(_fromUtf8("status_change_date_edit"))
        self.status_change_date_chbox = QtGui.QCheckBox(self.tab)
        self.status_change_date_chbox.setGeometry(QtCore.QRect(20, 305, 26, 17))
        self.status_change_date_chbox.setText(_fromUtf8(""))
        self.status_change_date_chbox.setObjectName(_fromUtf8("status_change_date_chbox"))
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(20, 285, 126, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(270, 15, 126, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.purpose_cbox = QtGui.QComboBox(self.tab)
        self.purpose_cbox.setGeometry(QtCore.QRect(270, 30, 196, 22))
        self.purpose_cbox.setObjectName(_fromUtf8("purpose_cbox"))
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(270, 60, 126, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.construction_type_cbox = QtGui.QComboBox(self.tab)
        self.construction_type_cbox.setGeometry(QtCore.QRect(270, 75, 196, 22))
        self.construction_type_cbox.setObjectName(_fromUtf8("construction_type_cbox"))
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(270, 100, 126, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.entry_type_cbox = QtGui.QComboBox(self.tab)
        self.entry_type_cbox.setGeometry(QtCore.QRect(270, 115, 196, 22))
        self.entry_type_cbox.setObjectName(_fromUtf8("entry_type_cbox"))
        self.label_12 = QtGui.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(270, 145, 126, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.location_cbox = QtGui.QComboBox(self.tab)
        self.location_cbox.setGeometry(QtCore.QRect(270, 160, 196, 22))
        self.location_cbox.setObjectName(_fromUtf8("location_cbox"))
        self.height_sbox = QtGui.QDoubleSpinBox(self.tab)
        self.height_sbox.setGeometry(QtCore.QRect(270, 205, 196, 22))
        self.height_sbox.setMinimum(-100.0)
        self.height_sbox.setMaximum(2000.0)
        self.height_sbox.setObjectName(_fromUtf8("height_sbox"))
        self.label_14 = QtGui.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(270, 190, 126, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(270, 235, 126, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.network_cbox = QtGui.QComboBox(self.tab)
        self.network_cbox.setGeometry(QtCore.QRect(270, 250, 196, 22))
        self.network_cbox.setObjectName(_fromUtf8("network_cbox"))
        self.date_of_last_inspection_edit = QtGui.QDateEdit(self.tab)
        self.date_of_last_inspection_edit.setEnabled(False)
        self.date_of_last_inspection_edit.setGeometry(QtCore.QRect(45, 205, 171, 22))
        self.date_of_last_inspection_edit.setCalendarPopup(True)
        self.date_of_last_inspection_edit.setObjectName(_fromUtf8("date_of_last_inspection_edit"))
        self.date_of_last_inspection_chbox = QtGui.QCheckBox(self.tab)
        self.date_of_last_inspection_chbox.setGeometry(QtCore.QRect(20, 210, 26, 17))
        self.date_of_last_inspection_chbox.setText(_fromUtf8(""))
        self.date_of_last_inspection_chbox.setObjectName(_fromUtf8("date_of_last_inspection_chbox"))
        self.label_13 = QtGui.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(20, 190, 126, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))

        self.retranslateUi(ManholeDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ManholeDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ManholeDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ManholeDialog)
        ManholeDialog.setTabOrder(self.tabWidget, self.manhole_no_edit)
        ManholeDialog.setTabOrder(self.manhole_no_edit, self.installation_date_chbox)
        ManholeDialog.setTabOrder(self.installation_date_chbox, self.installation_date_edit)
        ManholeDialog.setTabOrder(self.installation_date_edit, self.inspection_intervall_sbox)
        ManholeDialog.setTabOrder(self.inspection_intervall_sbox, self.inspection_intervall_unit_cbox)
        ManholeDialog.setTabOrder(self.inspection_intervall_unit_cbox, self.date_of_last_inspection_chbox)
        ManholeDialog.setTabOrder(self.date_of_last_inspection_chbox, self.date_of_last_inspection_edit)
        ManholeDialog.setTabOrder(self.date_of_last_inspection_edit, self.operating_state_cbox)
        ManholeDialog.setTabOrder(self.operating_state_cbox, self.status_change_date_chbox)
        ManholeDialog.setTabOrder(self.status_change_date_chbox, self.status_change_date_edit)
        ManholeDialog.setTabOrder(self.status_change_date_edit, self.purpose_cbox)
        ManholeDialog.setTabOrder(self.purpose_cbox, self.construction_type_cbox)
        ManholeDialog.setTabOrder(self.construction_type_cbox, self.entry_type_cbox)
        ManholeDialog.setTabOrder(self.entry_type_cbox, self.location_cbox)
        ManholeDialog.setTabOrder(self.location_cbox, self.height_sbox)
        ManholeDialog.setTabOrder(self.height_sbox, self.network_cbox)

    def retranslateUi(self, ManholeDialog):
        ManholeDialog.setWindowTitle(_translate("ManholeDialog", "Add / Edit Manhole", None))
        self.installation_date_edit.setDisplayFormat(_translate("ManholeDialog", "yyyy-MM-dd", None))
        self.label_3.setText(_translate("ManholeDialog", "Installation Date", None))
        self.label_5.setText(_translate("ManholeDialog", "Inspection Interval", None))
        self.label.setText(_translate("ManholeDialog", "Manhole Number", None))
        self.label_6.setText(_translate("ManholeDialog", "Inspection Interval Unit", None))
        self.label_7.setText(_translate("ManholeDialog", "Operating State", None))
        self.status_change_date_edit.setDisplayFormat(_translate("ManholeDialog", "yyyy-MM-dd", None))
        self.label_8.setText(_translate("ManholeDialog", "Date of Status Change", None))
        self.label_9.setText(_translate("ManholeDialog", "Purpose", None))
        self.label_10.setText(_translate("ManholeDialog", "Construction Type", None))
        self.label_11.setText(_translate("ManholeDialog", "Entry Type", None))
        self.label_12.setText(_translate("ManholeDialog", "Location", None))
        self.label_14.setText(_translate("ManholeDialog", "Height [m]", None))
        self.label_15.setText(_translate("ManholeDialog", "Network", None))
        self.date_of_last_inspection_edit.setDisplayFormat(_translate("ManholeDialog", "yyyy-MM-dd", None))
        self.label_13.setText(_translate("ManholeDialog", "Date of Last Inspection", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ManholeDialog", "Description", None))

import resources_rc
