# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UtilityStationDialog.ui'
#
# Created: Tue Oct 11 17:00:37 2016
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_UtilityStationDialog(object):
    def setupUi(self, UtilityStationDialog):
        UtilityStationDialog.setObjectName(_fromUtf8("UtilityStationDialog"))
        UtilityStationDialog.resize(588, 450)
        UtilityStationDialog.setMinimumSize(QtCore.QSize(588, 450))
        UtilityStationDialog.setMaximumSize(QtCore.QSize(588, 480))
        self.buttonBox = QtGui.QDialogButtonBox(UtilityStationDialog)
        self.buttonBox.setGeometry(QtCore.QRect(405, 400, 166, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.tabWidget = QtGui.QTabWidget(UtilityStationDialog)
        self.tabWidget.setGeometry(QtCore.QRect(15, 10, 556, 371))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.station_number_edit = QtGui.QLineEdit(self.tab)
        self.station_number_edit.setGeometry(QtCore.QRect(20, 30, 196, 20))
        self.station_number_edit.setObjectName(_fromUtf8("station_number_edit"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 15, 126, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(20, 240, 126, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.operating_state_cbox = QtGui.QComboBox(self.tab)
        self.operating_state_cbox.setGeometry(QtCore.QRect(20, 255, 196, 22))
        self.operating_state_cbox.setObjectName(_fromUtf8("operating_state_cbox"))
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(270, 16, 126, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.purpose_cbox = QtGui.QComboBox(self.tab)
        self.purpose_cbox.setGeometry(QtCore.QRect(270, 31, 196, 22))
        self.purpose_cbox.setObjectName(_fromUtf8("purpose_cbox"))
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(270, 60, 126, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.station_type_cbox = QtGui.QComboBox(self.tab)
        self.station_type_cbox.setGeometry(QtCore.QRect(270, 75, 196, 22))
        self.station_type_cbox.setObjectName(_fromUtf8("station_type_cbox"))
        self.label_12 = QtGui.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(270, 105, 126, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.location_cbox = QtGui.QComboBox(self.tab)
        self.location_cbox.setGeometry(QtCore.QRect(270, 120, 196, 22))
        self.location_cbox.setObjectName(_fromUtf8("location_cbox"))
        self.height_sbox = QtGui.QDoubleSpinBox(self.tab)
        self.height_sbox.setGeometry(QtCore.QRect(270, 165, 196, 22))
        self.height_sbox.setMinimum(-100.0)
        self.height_sbox.setMaximum(2000.0)
        self.height_sbox.setObjectName(_fromUtf8("height_sbox"))
        self.label_14 = QtGui.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(270, 150, 126, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(270, 195, 126, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.network_cbox = QtGui.QComboBox(self.tab)
        self.network_cbox.setGeometry(QtCore.QRect(270, 210, 196, 22))
        self.network_cbox.setObjectName(_fromUtf8("network_cbox"))
        self.station_name_edit = QtGui.QLineEdit(self.tab)
        self.station_name_edit.setGeometry(QtCore.QRect(20, 75, 196, 20))
        self.station_name_edit.setObjectName(_fromUtf8("station_name_edit"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 126, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.installation_year_sbox = QtGui.QDoubleSpinBox(self.tab)
        self.installation_year_sbox.setGeometry(QtCore.QRect(20, 120, 196, 22))
        self.installation_year_sbox.setDecimals(0)
        self.installation_year_sbox.setMaximum(3000.0)
        self.installation_year_sbox.setProperty("value", 0.0)
        self.installation_year_sbox.setObjectName(_fromUtf8("installation_year_sbox"))
        self.label_16 = QtGui.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(20, 105, 126, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.capacity_sbox = QtGui.QDoubleSpinBox(self.tab)
        self.capacity_sbox.setGeometry(QtCore.QRect(20, 165, 196, 22))
        self.capacity_sbox.setMinimum(0.0)
        self.capacity_sbox.setMaximum(200000.0)
        self.capacity_sbox.setObjectName(_fromUtf8("capacity_sbox"))
        self.capacity_unit_cbox = QtGui.QComboBox(self.tab)
        self.capacity_unit_cbox.setGeometry(QtCore.QRect(20, 210, 196, 22))
        self.capacity_unit_cbox.setObjectName(_fromUtf8("capacity_unit_cbox"))
        self.label_17 = QtGui.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(20, 150, 126, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_13 = QtGui.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(20, 195, 126, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(19, 285, 126, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.status_change_date_chbox = QtGui.QCheckBox(self.tab)
        self.status_change_date_chbox.setGeometry(QtCore.QRect(19, 305, 26, 17))
        self.status_change_date_chbox.setText(_fromUtf8(""))
        self.status_change_date_chbox.setObjectName(_fromUtf8("status_change_date_chbox"))
        self.status_change_date_edit = QtGui.QDateEdit(self.tab)
        self.status_change_date_edit.setEnabled(False)
        self.status_change_date_edit.setGeometry(QtCore.QRect(44, 300, 171, 22))
        self.status_change_date_edit.setCalendarPopup(True)
        self.status_change_date_edit.setObjectName(_fromUtf8("status_change_date_edit"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))

        self.retranslateUi(UtilityStationDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), UtilityStationDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), UtilityStationDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(UtilityStationDialog)
        UtilityStationDialog.setTabOrder(self.tabWidget, self.station_number_edit)
        UtilityStationDialog.setTabOrder(self.station_number_edit, self.station_name_edit)
        UtilityStationDialog.setTabOrder(self.station_name_edit, self.installation_year_sbox)
        UtilityStationDialog.setTabOrder(self.installation_year_sbox, self.capacity_sbox)
        UtilityStationDialog.setTabOrder(self.capacity_sbox, self.capacity_unit_cbox)
        UtilityStationDialog.setTabOrder(self.capacity_unit_cbox, self.operating_state_cbox)
        UtilityStationDialog.setTabOrder(self.operating_state_cbox, self.status_change_date_chbox)
        UtilityStationDialog.setTabOrder(self.status_change_date_chbox, self.status_change_date_edit)
        UtilityStationDialog.setTabOrder(self.status_change_date_edit, self.purpose_cbox)
        UtilityStationDialog.setTabOrder(self.purpose_cbox, self.station_type_cbox)
        UtilityStationDialog.setTabOrder(self.station_type_cbox, self.location_cbox)
        UtilityStationDialog.setTabOrder(self.location_cbox, self.height_sbox)
        UtilityStationDialog.setTabOrder(self.height_sbox, self.network_cbox)

    def retranslateUi(self, UtilityStationDialog):
        UtilityStationDialog.setWindowTitle(_translate("UtilityStationDialog", "Add / Edit Utility Station", None))
        self.label.setText(_translate("UtilityStationDialog", "Station Number", None))
        self.label_7.setText(_translate("UtilityStationDialog", "Operating State", None))
        self.label_9.setText(_translate("UtilityStationDialog", "Purpose", None))
        self.label_11.setText(_translate("UtilityStationDialog", "Station Type", None))
        self.label_12.setText(_translate("UtilityStationDialog", "Location", None))
        self.label_14.setText(_translate("UtilityStationDialog", "Height [m]", None))
        self.label_15.setText(_translate("UtilityStationDialog", "Network", None))
        self.label_2.setText(_translate("UtilityStationDialog", "Station Name", None))
        self.label_16.setText(_translate("UtilityStationDialog", "Installation Year", None))
        self.label_17.setText(_translate("UtilityStationDialog", "Capacity", None))
        self.label_13.setText(_translate("UtilityStationDialog", "Capacity Unit", None))
        self.label_8.setText(_translate("UtilityStationDialog", "Date of Status Change", None))
        self.status_change_date_edit.setDisplayFormat(_translate("UtilityStationDialog", "yyyy-MM-dd", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("UtilityStationDialog", "Description", None))

import resources_rc
